# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2222/eureka
  instance:
    statusPageUrlPath: /infoCatalogo
    healthCheckUrlPath: /healthCatalogo
    metadataMap:
      appOwner: valderasroldan
      description: aplicación ejemplo microservicios

# HTTP Server
server:
  port: ${PORT:1111}   # HTTP (Tomcat) port

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:7777/user
spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/expenses
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

